version: "3.9"
services:
  rtmp:
    container_name: server_rtmp
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8000:8000"
    depends_on:
      - auth
  client:
    build: ./client
    ports:
      - "80:80"
    container_name: server_client
    depends_on:
      - rtmp
  auth:
    build: ./auth
    container_name: server_auth
